/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp06.view;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tp06.model.Aluno;
import java.util.HashSet;
import java.util.Set;
import java.util.Random;

/**
 *
 * @author joao
 */
public class AbrirTurmasView extends javax.swing.JFrame{

    /**
     * Creates new form AbrirTurmasView
     */
    public AbrirTurmasView() {
        initComponents();
        //preencherTabelas();
        preencherDisciplinasComboBox();
        gerarCodigoAleatoriamente();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jTextID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdisc = new javax.swing.JTextField();
        jBAbrir = new javax.swing.JButton();
        jCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBpesquisar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jCursoBox = new javax.swing.JComboBox<>();
        jInstBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jCBHorario = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextCarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCBsemana = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jToggleButton1.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/search_16.png")); // NOI18N
        jToggleButton1.setText("Pesquisar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 59, -1));

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 30, -1));

        jNome.setEnabled(false);
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 250, -1));

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jdisc.setEnabled(false);
        getContentPane().add(jdisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 220, -1));

        jBAbrir.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/document_16.png")); // NOI18N
        jBAbrir.setText("Abrir Turma");
        jBAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(jBAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 632, -1, -1));

        jCodigo.setEnabled(false);
        getContentPane().add(jCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 140, -1));

        jLabel5.setText("Código de Turma:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 35));

        jBpesquisar.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/search_16.png")); // NOI18N
        jBpesquisar.setText("Pesquisar");
        jBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/left_16.png")); // NOI18N
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 632, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, -4, 522, 630));

        jLabel6.setText("Curso que vai receber as aulas:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 318, -1, -1));

        jCursoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Sistemas de Informação", "Engenharia de Computação", "Ciência da Computação", "Engenharia de Software", "Design Digital", "Redes de Computadores" }));
        getContentPane().add(jCursoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 342, 251, -1));

        jInstBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "UFC - Campus Quixadá", "UFC - Campus Pici", "UFC - Campus Sobral", "UFC - Campus Russas", "UFC - Campus Crateús" }));
        getContentPane().add(jInstBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 407, 251, -1));

        jLabel8.setText("Instituição de Ensino:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 383, -1, -1));

        jCBHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione....", "08h-10h", "10h-12h", "13h30-15h30", "15h30-17h30", "18h-20h", "20h-22h" }));
        getContentPane().add(jCBHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 472, 251, -1));

        jLabel9.setText("Horario de Aula:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 448, -1, -1));

        jTextCarga.setEnabled(false);
        getContentPane().add(jTextCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 80, -1));

        jLabel10.setText("CH:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 30, -1));

        jLabel11.setText("Dia da semana:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 513, -1, -1));

        jCBsemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Segunda", "Terça", "Quarta", "Quinta", "Sexta" }));
        getContentPane().add(jCBsemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 537, 251, -1));

        jPanel1.setBackground(java.awt.Color.black);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Abrindo Turmas");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Digite o ID do professor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 50));

        jLabel4.setText("Disciplina:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel2.setBackground(java.awt.Color.black);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Informações da turma");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 310, 50));

        jLabel13.setForeground(java.awt.Color.gray);
        jLabel13.setText("Powered by: Mr.Uzumaki");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 680, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    public boolean verificarProfessor(){
        //preencherTabelas();
        try{
            FileInputStream abrir = new FileInputStream("RegistrosdeProfessores.txt");
            InputStreamReader input = new InputStreamReader(abrir);
            BufferedReader br = new BufferedReader(input);
            
            String linha = null;
            do{
                linha = br.readLine();
                if(linha != null){
                    String[] palavras = linha.split(";");
                    for(int i = 0; i < palavras.length; i++){
                        if(jTextID.getText().equals(palavras[i])){
                            //preencherTabelas();
                            jNome.setText(palavras[i-3]);
                            jdisc.setText(palavras[i+4]);
                            preencherTabelas();
                            return true;
                        }
                    }
                }
                
            }while(linha != null);
            
        }catch(Exception e){
            
        }
        return false;
    }
    //Gerando codigos de turma aleatoriamente
    private void gerarCodigoAleatoriamente(){
        Random gerador = new Random();
        for(int i = 0; i < 1000; i++){
            jCodigo.setText(Integer.toString(gerador.nextInt(1000)));
            
        }
    }
    //Limpando campos do jTable
    private void limparCampos(){
        jCodigo.setText("");
        jNome.setText("");
        jTextID.setText("");
        jdisc.setText("");
        jCodigo.setText("");
        
        int k = 0,j = 0, rowTable = 0, columnTable = 1;
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int x = jTable1.getRowCount();
        for(int i = 0; i < x; i++){
            modelo.setValueAt("", k, j);
            modelo.setValueAt("", rowTable, columnTable);
            rowTable++;
            k++;
            
        }
        jCursoBox.setSelectedItem("Selecione...");
        jInstBox.setSelectedItem("Selecione...");
        jCBHorario.setSelectedItem("Selecione....");
    }
    //Pesquisar registros de Professores
    private void jBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarActionPerformed
        // TODO add your handling code here:
        if(!verificarProfessor())
            JOptionPane.showMessageDialog(null, "Professor inexistente");
        pegarCargaHoraria();
    }//GEN-LAST:event_jBpesquisarActionPerformed
    //Pegando carga horária do arquivo
    private void pegarCargaHoraria(){
        try{
            FileInputStream abrir = new FileInputStream("Disciplinas.txt");
            InputStreamReader input = new InputStreamReader(abrir);
            BufferedReader br = new BufferedReader(input);
            
            String linha;
            String[] palavras;
            
            while((linha = br.readLine()) != null){
                if(linha != null){
                    palavras= linha.split(";");
                    
                    for(int i = 0; i < palavras.length; i++){
                        if(jdisc.getText().equals(palavras[i]))
                            jTextCarga.setText(palavras[1]);
                        
                    }
                    
                }
                
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    //Preenchendo tabelas com registros de alunos
    private void preencherTabelas(){
        try{
            FileInputStream abrirArquivo = new FileInputStream("Alunos.txt");
            InputStreamReader inputTable = new InputStreamReader(abrirArquivo);
            BufferedReader br1 = new BufferedReader(inputTable);
            
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            
            String linha1 = null;
            //do{
            int i = 0, j = 0;
            int rowTable = 0, columnTable = 1;
            while((linha1 = br1.readLine()) != null){
                if(linha1 != null){
                    Object[] palavras1 = linha1.split(";");
                    //for (Object palavras2 : palavras1) {
                    for (Object palavras11 : palavras1) {
                        if (jCursoBox.getSelectedItem().equals(palavras11) && jInstBox.getSelectedItem().equals(palavras1[5])) {
                            //for(int i = 0; i < palavras1.length; i++){
                            modelo.setValueAt(palavras1[0], i, j);
                            modelo.setValueAt(palavras1[3], rowTable, columnTable);
                         
                            i++;
                            rowTable ++;
                            break;
                            //}
                        }
                    }
                    //}
                }
            }
            //}while(linha1 != null);
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Arquivo não foi aberto");
        }
    }
    //Coloca as disciplinas adicionadas em adicionar Disciplinas automaticamente no comboBox
    private void preencherDisciplinasComboBox(){
        String[] palavras = null;
        try{
            FileInputStream arquivo = new FileInputStream("CursosAdicionados.txt");
            InputStreamReader input = new InputStreamReader(arquivo);
            BufferedReader br = new BufferedReader(input);
            
            String linha = null;
            do{
                linha = br.readLine();
                if(linha != null){
                    palavras = linha.split(";");
                    for(int i = 0; i < palavras.length; i++){
                        jCursoBox.addItem(palavras[i]);
                        break;   
                    }
                }
               
            }while(linha != null);
            
            
        }catch(Exception e){
            
        }
       
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SecretariaCadastrosView secCadV = new SecretariaCadastrosView();
        secCadV.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked
    //Pegando as informações passadas nos JtextsFields
    public boolean aberturaDeTurma(){
        //preencherTabelas();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        if(!verificarHorarioAluno()){
            try{
                FileWriter criarArquivo = new FileWriter("TurmasAbertas.txt", true);
                PrintWriter gravarArquivo = new PrintWriter(criarArquivo);


                gravarArquivo.print(jNome.getText() + ";" + jTextID.getText() + ";"+ jCodigo.getText() +"A"+ ";" +jCursoBox.getSelectedItem() + ";" + jInstBox.getSelectedItem() + ";" + jdisc.getText() + ";" + jTextCarga.getText() +";"+ jCBHorario.getSelectedItem()+ ";" + jCBsemana.getSelectedItem()+ ";" +"\n");
                int x = jTable1.getRowCount();
                for(int i = 0; i < x + 1; i++){
                    for(int j = 0; j < x + 1; j++){
                        if(modelo.getValueAt(j, 0) == null)
                            break;
                        //Código da turma
                        gravarArquivo.print(jCodigo.getText() + ";");
                        //Informações do aluno Nome e CPF
                        gravarArquivo.print(modelo.getValueAt(j, 0) + ";");
                        gravarArquivo.print(modelo.getValueAt(j, 1) + ";");
                        gravarArquivo.print(jdisc.getText() + ";" + jNome.getText() + ";" + jCBHorario.getSelectedItem() +";" + jCBsemana.getSelectedItem()+ ";"+"\n");
                    }
                    break;
                }
                gravarArquivo.close();
                criarArquivo.close();
                
                return true;
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e + " aqui");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Alunos já cadastrado nesse horário");
        }
        
        return false;
    }
    //Metodo para verificar se aluno ja tem aula no horario definido
    private boolean verificarHorarioAluno(){
        try{
            FileInputStream abrir = new FileInputStream("TurmasAbertas.txt");
            InputStreamReader input = new InputStreamReader(abrir);
            BufferedReader br = new BufferedReader(input);
            
            String percorrer_linhas;
            String[] percorrer_palavras;
            
            while((percorrer_linhas = br.readLine()) != null){
                if(percorrer_linhas != null){
                    percorrer_palavras = percorrer_linhas.split(";");
                    
                    for(int i = 0; i <= percorrer_palavras.length - (percorrer_palavras.length - 1); i++){
                        if(jCBHorario.getSelectedItem().equals(percorrer_palavras[i]) && jCBsemana.getSelectedItem().equals(percorrer_palavras[8])){
                            return true;
                        }
                    }
                    
                }
                
            }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        return false;
    }
    private void jBAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirActionPerformed
        // TODO add your handling code here:
        if(aberturaDeTurma()){
            JOptionPane.showMessageDialog(null, "Turma aberta");
            limparCampos();
        }else{ 
            JOptionPane.showMessageDialog(null, "Turma não aberta");
        }
    }//GEN-LAST:event_jBAbrirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbrirTurmasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbrirTurmasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbrirTurmasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirTurmasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbrirTurmasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbrir;
    private javax.swing.JButton jBpesquisar;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCBHorario;
    private javax.swing.JComboBox<String> jCBsemana;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JComboBox<String> jCursoBox;
    private javax.swing.JComboBox<String> jInstBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCarga;
    private javax.swing.JTextField jTextID;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jdisc;
    // End of variables declaration//GEN-END:variables
}
