/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp06.view;

import java.awt.List;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import tp06.model.Pessoa;
import tp06.model.Professor;
import java.util.Random;

/**
 *
 * @author joao
 */
public class CadastrarProfessorView extends javax.swing.JFrame {
    ArrayList<Professor> professores = new ArrayList<>();
    /**
     * Creates new form CadastrarProfessorView
     */
    public CadastrarProfessorView() {
        initComponents();
        preencherDisciplinasComboBox();
        gerarIDProfessorAleatoriamente();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCpf = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("###.###.###-##");
            jCpf = new javax.swing.JFormattedTextField(cpf);
        }
        catch (Exception e){
        }
        jLabel4 = new javax.swing.JLabel();
        jIdade = new javax.swing.JTextField();
        jSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jIDText = new javax.swing.JTextField();
        jLogin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSenha = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBinst = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jCBdisc = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 580));
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 80, 220, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel3.setText("Cpf:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(jCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 120, 220, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel4.setText("Idade(em anos):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(jIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 55, -1));

        jSalvar.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/save_16.png")); // NOI18N
        jSalvar.setText("Salvar");
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 110, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/left_16.png")); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 90, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel5.setText("ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jIDText.setEnabled(false);
        getContentPane().add(jIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 60, -1));
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 220, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel6.setText("Login:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel7.setText("Senha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 220, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Login e Senha de Acesso ao sistema");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel9.setText("Instituição:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jCBinst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "UFC - Campus Quixadá", "UFC - Campus Pici", "UFC - Campus Sobral", "UFC - Campus Russas", "UFC - Campus Crateús" }));
        getContentPane().add(jCBinst, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 220, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel10.setText("Disciplina:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jCBdisc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));
        jCBdisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBdiscActionPerformed(evt);
            }
        });
        getContentPane().add(jCBdisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 220, -1));

        jPanel1.setBackground(java.awt.Color.black);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Cadastro de Professores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 40));

        jLabel11.setForeground(java.awt.Color.lightGray);
        jLabel11.setText("Powered by: Mr.Uzumaki");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, -1));

        jPanel2.setBackground(java.awt.Color.black);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 410, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
        // TODO add your handling code here:
        //Adicionando o que foi preenchido nos JtextField ao Construtor de Professor
        try{
            FileWriter fw = new FileWriter("RegistrosdeProfessores.txt", true);
            PrintWriter pw = new PrintWriter(fw);
            
            pw.println(jNome.getText() + ";" + jCpf.getText() + ";" + jIdade.getText() + ";" + jIDText.getText() + ";" + jLogin.getText() + ";" + jSenha.getText() + ";" + jCBinst.getSelectedItem() + ";" + jCBdisc.getSelectedItem());
            JOptionPane.showMessageDialog(null, "Professor adicionado");
            pw.close();
            
        }catch(Exception e){
            
        }
        professores.add(new Professor(jNome.getText(), jCpf.getText(), Integer.parseInt(jIdade.getText()), Integer.parseInt(jIDText.getText())));
        jNome.setText("");
        jCpf.setText("");
        jIdade.setText("");
        jIDText.setText("");
        jLogin.setText("");
        jSenha.setText("");
    }//GEN-LAST:event_jSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuReitor mr = new MenuReitor();
        mr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void preencherDisciplinasComboBox(){
        String[] palavras = null;
        try{
            FileInputStream arquivo = new FileInputStream("Disciplinas.txt");
            InputStreamReader input = new InputStreamReader(arquivo);
            BufferedReader br = new BufferedReader(input);
            
            String linha = null;
            do{
                linha = br.readLine();
                if(linha != null){
                    palavras = linha.split(";");
                    for(int i = 0; i < palavras.length; i++){
                        jCBdisc.addItem(palavras[i]);
                        break;   
                    }
                }
               
            }while(linha != null);
            
            
        }catch(Exception e){
            
        }
       
    }
    private void jCBdiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBdiscActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jCBdiscActionPerformed
    //Gerando disciplinas aleatórias
    private void gerarIDProfessorAleatoriamente(){
        Random gerador = new Random();
        for(int k = 0; k < 1000; k++){
            jIDText.setText(Integer.toString(gerador.nextInt(1000)));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProfessorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBdisc;
    private javax.swing.JComboBox<String> jCBinst;
    private javax.swing.JTextField jCpf;
    private javax.swing.JTextField jIDText;
    private javax.swing.JTextField jIdade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLogin;
    private javax.swing.JTextField jNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jSalvar;
    private javax.swing.JPasswordField jSenha;
    // End of variables declaration//GEN-END:variables
}
