/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp06.view;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import tp06.model.Pessoa;
import tp06.model.Professor;

/**
 *
 * @author joao
 */
public class LancarNotas extends javax.swing.JFrame {
    Pessoa professor = new Professor();
    /**
     * Creates new form LancarNotas
     */
    public LancarNotas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCodigoField = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextDisc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextCH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Lançamento de notas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 12, -1, -1));

        jLabel3.setText("Código de Turma:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 66, -1, -1));
        getContentPane().add(jCodigoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 218, -1));

        jBPesquisar.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/search_16.png")); // NOI18N
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/statistics_16.png")); // NOI18N
        jButton1.setText("Lançar Notas e Faltas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, -1, -1));

        jTextDisc.setEnabled(false);
        getContentPane().add(jTextDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 172, -1));

        jLabel2.setText("Disciplina:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/left_16.png")); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, -1, -1));

        jInternalFrame1.setTitle("Notas e Faltas");
        jInternalFrame1.setVisible(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "ID", "Nota 1", "Nota 2", "Nota 3", "Faltas(em horas)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 190, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 740, -1));

        jTextCH.setEnabled(false);
        getContentPane().add(jTextCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 62, -1));

        jLabel4.setText("Créditos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanel1.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 50));

        jLabel5.setForeground(java.awt.Color.lightGray);
        jLabel5.setText("Powered by: Mr.Uzumaki");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 690, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
        pesquisaCodigodeTurma();
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(pegarValorDoTable())
            JOptionPane.showMessageDialog(null, "Notas adicionadas com sucesso");
        else 
            JOptionPane.showMessageDialog(null, "Notas não adicionadas");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ViewProfessor vprof = new ViewProfessor();
        vprof.setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    //Pesquisando pelo codigo de turma
    public void pesquisaCodigodeTurma(){
        try{
            FileInputStream abrir = new FileInputStream("TurmasAbertas.txt");
            InputStreamReader leitor = new InputStreamReader(abrir);
            BufferedReader br = new BufferedReader(leitor);
            
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            
            String percorrer_linhas;
            int percorrerNome = 1, linhaTabela = 0, colunaTabela = 0, columnTable = 1;
            while((percorrer_linhas = br.readLine()) != null){
                String[] palavras;
                if(percorrer_linhas != null){
                    palavras = percorrer_linhas.split(";");
                    
                    for(int i = 0; i < palavras.length; i++){
                        if(jCodigoField.getText().equals(palavras[i])){
                            modelo.setValueAt(palavras[percorrerNome], linhaTabela, colunaTabela);
                            modelo.setValueAt(palavras[2], linhaTabela, columnTable);
                            linhaTabela++;
                            
                           
                        }
                        
                    }
                    if((jCodigoField.getText()+"A").equals(palavras[2])){
                        jTextDisc.setText(palavras[5]);
                        jTextCH.setText(palavras[6]);
                    }
                    
                }
                
            }
            
        }catch(Exception e){
            
        }
    }
    //Pegando os valores digitados diretamente na tabeal
    private boolean pegarValorDoTable(){
        double media = 0.0;
        try{
            FileWriter criar = new FileWriter("Notas.txt", true);
            PrintWriter escrever = new PrintWriter(criar);
            
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            
            int x = jTable1.getColumnCount();
            for(int i = 0; i < x; i++){
                escrever.print(modelo.getValueAt(0, i) + ";");
               
            }
            escrever.print(jTextDisc.getText() + ";");
            escrever.print("64" + ";");
            escrever.print("\n");
            for(int j = 0; j < x; j++){
                escrever.print(modelo.getValueAt(1, j) + ";");
                
            }
            escrever.print(jTextDisc.getText() + ";");
            escrever.print("64" + ";");
            
            escrever.print("\n");
            for(int k = 0; k < x; k++){
                escrever.print(modelo.getValueAt(2, k) + ";");
                
            }
            escrever.print(jTextDisc.getText() + ";");
            escrever.print("64" + ";");
            escrever.print("\n");
            for(int l = 0; l < x; l++){
                escrever.print(modelo.getValueAt(3, l) + ";");
                
            }
            escrever.print(jTextDisc.getText() + ";");
            escrever.print("64" + ";");
            escrever.print("\n");
            for(int q = 0; q < x; q++){
                escrever.print(modelo.getValueAt(4, q) + ";");
            }
            escrever.print(jTextDisc.getText() + ";" + jTextCH.getText() + ";");
            escrever.print("64" + ";");
            escrever.print("\n");
            //Calcula Média
           
            escrever.close();
            criar.close();
            return true;
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Arquivo não aberto");
        }
        return false;
    }
    public void setLoginProfessor(int _id){
        professor.setId(_id);
        
    }
    public int retornarID(){
        return professor.getId();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancarNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCodigoField;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCH;
    private javax.swing.JTextField jTextDisc;
    // End of variables declaration//GEN-END:variables
}
