/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp06.view;
import tp06.model.Reitor;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import tp06.model.Aluno;
import tp06.model.Historico;
import tp06.model.Pessoa;


/**
 *
 * @author joao
 */
public class MenuPrincipal extends javax.swing.JFrame {
    //ArrayList<Aluno> aluno = new ArrayList<Aluno>();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() { 
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }
    HistoricoEscolar historico = new HistoricoEscolar();
    ViewProfessor viewPro = new ViewProfessor();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLogin = new javax.swing.JTextField();
        jSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jCBSelecao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);

        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Senha:");

        jCBSelecao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Reitor", "Coordenador", "Professor", "Secretaria", "Aluno" }));
        jCBSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSelecaoActionPerformed(evt);
            }
        });

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Tipo de conta:");

        jButton1.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/tick_16.png")); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("/home/joao/Documentos/CADEIRAS/POO/Pack de imagens/delete_16.png")); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Login:");

        jPanel1.setBackground(java.awt.Color.darkGray);

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 0, 56)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("SACD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setForeground(java.awt.Color.lightGray);
        jLabel5.setText("Powered by: Mr.Uzumaki");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel3)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    AlunoInterface alunoIn = new AlunoInterface();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLogin.setText("");
        jSenha.setText("");
        jCBSelecao.setSelectedItem("Selecionar...");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    //Testando se existem registros do Aluno que acessou o sistema
    private  boolean validacaoAluno(){
        try {   
            FileInputStream arquivo = new FileInputStream("AlunoLogineSenha.txt");
            InputStreamReader input = new InputStreamReader(arquivo);
            BufferedReader br = new BufferedReader(input);

            String linha = null;
            do{
                linha = br.readLine();
                
                if(linha != null){
                    String[] palavras = linha.split(";");
                    for(int i = 0; i < palavras.length; i++){
                        if(jLogin.getText().equals(palavras[i]) && new String(jSenha.getPassword()).equals(palavras[i+1])){
                            alunoIn.ajustarValor(Integer.parseInt(palavras[2]));
                            //historico.setIDAluno(Integer.parseInt(palavras[2]));
                            return true;
                        }
                    }
                }
            }while(linha != null);
            br.close();
            input.close();
            arquivo.close();
            
        } catch (FileNotFoundException e) {
            System.out.println("Arquivo não aberto, HERE!!!!!!");
            
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    
    //Testando se existe registros do professor que está acessando.
    private boolean validacaoProfessor(){
        boolean retorno = false;
        try {
            FileInputStream arquivo = new FileInputStream("RegistrosdeProfessores.txt");
            InputStreamReader input = new InputStreamReader(arquivo);
            BufferedReader br = new BufferedReader(input);

            String linha = null;
            do{
                linha = br.readLine();
                
                if(linha != null){
                    String[] palavras = linha.split(";");
                    for(int i = 0; i < palavras.length; i++){
                        if(jLogin.getText().equals(palavras[i]) && new String(jSenha.getPassword()).equals(palavras[i+1])){
                            viewPro.setIDProfessor(Integer.parseInt(palavras[3]));
                            return true;
                        }
                        
                    }
                }
            }while(linha != null);
            br.close();
            input.close();
            arquivo.close();
            
        } catch (Exception e) {
            System.out.println("Arquivo não aberto");
        }
        return false;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Abrindo arquivo Aluno.txt para validar logins e senhas
        if(jLogin.getText().equals("Reitor") && new String(jSenha.getPassword()).equals(new String("1234")) && jCBSelecao.getSelectedItem() == "Reitor"){
            MenuReitor menuR = new MenuReitor();
            menuR.setVisible(true);
            dispose();

        }else if(jLogin.getText().equals("Coo") && new String(jSenha.getPassword()).equals(new String("1234")) && jCBSelecao.getSelectedItem() == "Coordenador"){
            AdicionarDisciplinasByCoo ad = new AdicionarDisciplinasByCoo();
            ad.setVisible(true);
            dispose();

        }else if(jCBSelecao.getSelectedItem() == "Aluno"){
            if(validacaoAluno()){
                //AlunoInterface alunoIn1 = new AlunoInterface();
                alunoIn.setVisible(true);
                dispose();
                //AlunoInterface aluno = new AlunoInterface();
              
            }else{
                JOptionPane.showMessageDialog(null, "Aluno inexistente ou informações incorretas");
                jLogin.setText("");
                jSenha.setText("");
                
            }
            
        }else if(jCBSelecao.getSelectedItem() == "Professor"){
            if(validacaoProfessor()){
                //ViewProfessor professorview = new ViewProfessor();
                viewPro.setVisible(true);
                dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "Professor inexistente ou informações incorretas");
                jLogin.setText("");
                jSenha.setText("");
                
            }
            
        }else if(jLogin.getText().equals("Secretaria") && new String(jSenha.getPassword()).equals(new String("1234")) && jCBSelecao.getSelectedItem() == "Secretaria"){
            SecretariaCadastrosView secCad = new SecretariaCadastrosView();
            secCad.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Senha e/ou Usuário incorretos");
        }
        jLogin.setText("");
        jSenha.setText("");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCBSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSelecaoActionPerformed

    }//GEN-LAST:event_jCBSelecaoActionPerformed
    //Retornar o login do usuário para que o sistema saiba quem está acessando
    public String pegarCPFAluno(){
        //AlunoInterface alunoIn = new AlunoInterface();
        try{
            FileInputStream abrir = new FileInputStream("AlunoLogineSenha.txt");
            InputStreamReader input = new InputStreamReader(abrir);
            BufferedReader br = new BufferedReader(input);
            
            String percorrer_linhas;
            
            while((percorrer_linhas = br.readLine()) != null){
                if(percorrer_linhas != null){
                    String[] palavras = percorrer_linhas.split(";");
                    
                    //for(int i = 0; i < palavras.length; i++){
                        if(jLogin.getText().equals(palavras[0]))
                            //alunoIn.setLoginAluno(palavras[2]);
                            return palavras[2];
                        
                    //}
                    
                    
                }
                
            }
            
        }catch(Exception e){
            
        }
        return "Erro";
        
    }
    
    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBSelecao;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jSenha;
    // End of variables declaration//GEN-END:variables
  

}
